[build]
  # Directory to serve files from
  publish = "."

[build.environment]
  # Node.js version for build process (not needed for static sites, but good to specify)
  NODE_VERSION = "18"

# Redirect rules for single-page applications (optional)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Development settings
[dev]
  command = "echo 'No build command needed for static site'"
  port = 8888
  publish = "."
